### ISSUE TITLE
有没有自动订阅的功能

### ISSUE THREAD

**Issue by huifukejian** [TheCGDF/SSD-Windows#19]
偶尔要手动订阅～

**Comment by huifukejian** [comment]
没有的话，能不能加上

**Comment by CGDF-Github** [comment]
旧版SSD倒是有自动更新订阅，当时直接照搬了SSR的更新策略，但是事实证明这种策略在SSD上会造成很多冲突，于是后来便移除了这一设计。
不过下个版本会尝试使用一种更加严格细化的方法恢复这个功能。用户可以自行选择哪些订阅需要开启自动更新，不需要的则不开启，同时将可以自定义时间间隔。

**Comment by huifukejian** [comment]
期待更新！

**Comment by TheCGDF** [comment]
考量之后还是决定放弃自动更新，更新依然依赖于用户手动操作
