### ISSUE TITLE
Subscription spec in wiki is wrong

### ISSUE THREAD

**Issue by balthild** [TheCGDF/SSD-Windows#21]
https://github.com/TheCGDF/SSD-Windows/wiki/%E8%AE%A2%E9%98%85%E5%8D%8F%E5%AE%9A%EF%BC%88http%EF%BC%89
https://github.com/TheCGDF/SSD-Windows/wiki/Subscription-Specification-(http)

The wiki says

Name/value pair (w/ sample values) | Type
-- | --
"id":3 | OPTIONAL

But the code https://github.com/TheCGDF/SSD-Windows/blob/master/shadowsocks-csharp/_SSD/Model/Subscription/Subscription.Public.cs#L126 will fail if the id isn't set.

I'd wonder if it's a bug in the code, or a mistake in wiki.

**Comment by TheCGDF** [comment]
Fixed:
https://github.com/TheCGDF/SSD-Windows/compare/17eb7b9ce46f...9c84f321a3b7

Thanks.
