### ISSUE TITLE
编辑服务器时服务器显示框能调整一下吗？

### ISSUE THREAD

**Issue by HHSSRR** [TheCGDF/SSD-Windows#22]
编辑服务器时服务器显示框能调大一些吗？看不完服务器名称和节点，和SSRR一样大就好了！

**Comment by HHSSRR** [comment]
编辑服务器时 服务器显示框能调大一些吗？看不完服务器

**Comment by HHSSRR** [comment]
![QQ截图20190513134309](https://user-images.githubusercontent.com/50567415/57598242-10889f00-7585-11e9-8cd8-1324c0c21829.png)

**Comment by TheCGDF** [comment]
https://github.com/TheCGDF/SSD-Windows/commit/4546b9281b1917ef03aa79f3d436d642b251c80d

刚刚的commit尝试裁剪了前缀显示，现在的话，你的机场应该会显示为`[Cord..] 香港HKTF打机神线`这样，虽然没有调整宽度，但是应该也可以很好工作了

**Comment by HHSSRR** [comment]
> [4546b92](https://github.com/TheCGDF/SSD-Windows/commit/4546b9281b1917ef03aa79f3d436d642b251c80d)
> 
> 刚刚的提交尝试裁剪了前缀显示，现在的话，的你应该机场会显示为`[Cord..] 香港HKTF打机神线`这样，虽然没有调整宽度，但是应该也可以很好工作了

是下个版本 还是在软件内设置？

**Comment by TheCGDF** [comment]
@HHSSRR 下个版本

**Comment by HHSSRR** [comment]
好的 期待一下！

**Comment by hyy34** [comment]
> @HHSSRR 下个版本

感觉把框体加大些。就应该什么都解决了。
