### ISSUE TITLE
提交错误

### ISSUE THREAD

**Issue by LFKazusa** [TheCGDF/SSD-Windows#24]
![@Z 0Y$7@PM8`CPSQDGUZSDG](https://user-images.githubusercontent.com/45877692/58751665-dfd8bd00-84d3-11e9-9fd1-1cd8458ea267.png)

**Comment by TheCGDF** [comment]
请勿在c盘运行，否则需要授权访问

**Comment by HHSSRR** [comment]
> 请勿在Ç盘运行，否则需要授权访问
大佬 0.1.8多久更新啊？

**Comment by Un1Gfn** [comment]
催更？活著不好嗎
