### ISSUE TITLE
订阅地址 & 符号后面内容会被删去。

### ISSUE THREAD

**Issue by ivechan** [TheCGDF/SSD-Windows#25]
软件版本：0.1.7
复现步骤：
1. 输入这种类型的订阅地址：https://example.com/link/xxxxxxx?mu=3&class=3
2. 订阅更新，这时候是正常的。
3. 重启软件，再订阅更新，会发现地址变成了 https://example.com/link/xxxxxxx?mu=3 **&class=3** ，即 **&** 符号后面的内容被删除
4. 看 gui-config.json 发现确实也被删除。

**Comment by TheCGDF** [comment]
![chrome_9jJgFq41TX](https://user-images.githubusercontent.com/17256673/60248704-c7eb3200-98f5-11e9-8b72-0f866f6335ef.jpg)
自行确认一下你订阅json的url字段

**Comment by ivechan** [comment]
1. 刚刚确认了 gui-config.json 文件中， url 字段是没有 **&class=3** （当然我添加订阅的时候是有输入的）。
2. 我尝试关闭 SSD，然后强行修改在 url 字段加入 **&class=3** 后启动 SSD，此时SSD 不显示订阅信息，并且配置文件中的订阅信息也被删除。

**Comment by TheCGDF** [comment]
@ivechan 那说明你的SSD订阅是不符合规范的，url字段是从订阅中获取的，请找你的机场主修复
