### ISSUE TITLE
绕过中国大陆和常用网址 希望加上

### ISSUE THREAD

**Issue by hyy34** [TheCGDF/SSD-Windows#26]
希望大佬能把这个功能加上，用pac连github都不走代理了。。。而且还找不到好的pac，大佬用的哪的pac？

**Comment by sharuijinfriend** [comment]
https://raw.githubusercontent.com/sharuijinfriend/pac/master/pacicbase/out.pac

**Comment by timeneverdie** [comment]
> https://raw.githubusercontent.com/sharuijinfriend/pac/master/pacicbase/out.pac

测试可用，希望可以长期更新。适配SS的white**ip**.pac真的非常非常少。
