### ISSUE TITLE
Win10 1809出现非预期错误

### ISSUE THREAD

**Issue by kaisyaliu** [TheCGDF/SSD-Windows#32]
√ 提交BUG

[2019-11-21 10:57:57] [E] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 Shadowsocks.Controller.Strategy.StatisticsStrategy..ctor(ShadowsocksController controller)
   在 Shadowsocks.Controller.Strategy.StrategyManager..ctor(ShadowsocksController controller)
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()

**Comment by kaisyaliu** [comment]
并没有在C盘运行，与前面的问题解决方法不一样。

**Comment by TheCGDF** [comment]
@kaisyaliu 请说明导致bug的操作

**Comment by kaisyaliu** [comment]
下载独立运行的exe文件的时候，是可以正常运行的，使用订阅功能更新订阅之后退出程序就会报此错误，应该是更新订阅里的内容导致报错。

**Comment by kaisyaliu** [comment]
OK！我找到大概的原因了，如果删掉默认的那个baidu服务器，并更新之后，就会有这个错误。

**Comment by TheCGDF** [comment]
@kaisyaliu 所以步骤是：启动；导入订阅；删除baidu；更新订阅；退出；报错；
这样吗？

**Comment by kaisyaliu** [comment]
是的！我是先更新订阅再删除baidu，不过我感觉应该是一样的。这个问题只要这样操作，必现。

**Comment by TheCGDF** [comment]
@kaisyaliu 版本是0.1.7吗？似乎无法复现的样子

**Comment by kaisyaliu** [comment]
我的版本是在机场下的，有可能是因为不是最新版导致，我再找个0.1.7试试。
