### ISSUE TITLE
win7 simple-obfs使用一段时间会弹出错误

### ISSUE THREAD

**Issue by TaessicaDae** [TheCGDF/SSD-Windows#33]
![微信图片_20191209204934](https://user-images.githubusercontent.com/25148545/70436980-7d392d00-1ac5-11ea-811c-7e564a66c757.png)

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	simple-obfs.exe
  应用程序版本:	0.0.0.0
  应用程序时间戳:	5a17f029
  故障模块名称:	simple-obfs.exe
  故障模块版本:	0.0.0.0
  故障模块时间戳:	5a17f029
  异常代码:	40000015
  异常偏移:	0000000000017d52
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	832d
  其他信息 2:	832d823b182c33a7d45ecabd2a20c133
  其他信息 3:	f667
  其他信息 4:	f66734b5956b735d97d00899d8a1bc89

**Comment by TheCGDF** [comment]
@TaessicaDae 这个可能得反馈至上游，然而上游已经停止维护simple obfs。你要么试着升级.net framework，要么试着升级win10吧

**Comment by TaessicaDae** [comment]
@TheCGDF ok,那我试试
