### ISSUE TITLE
可否加入一个选项用于取消自动的延迟测试？

### ISSUE THREAD

**Issue by poly-1** [TheCGDF/SSD-Windows#34]
issue的用途：

√ 申请新功能

---

当前SSD似乎默认会经常性的进行延时测试，选项没有找到可关闭的选项，亦没有找到可以调整每次延时测试的时间间隔的选项。本地json里面似乎也没有跟这个功能相关的item，希望后续可以加入这个功能。

**Comment by TheCGDF** [comment]
SSD不会自动测试延迟

**Comment by poly-1** [comment]
我可能没有表述清楚，我的意思是选择服务器的列表里面，每个服务器左边都有一个类似`[35 ms ...`字样的RTT，这个应该是定期自动测试出来的吧？

至少每次重启软件之后过段时间都会自动重测，从pending变成有具体数值的状态。能否把这个自动测试改为手动？

**Comment by TheCGDF** [comment]
我表述得很清楚，SSD没有自动测试延迟，请确保自己下载的不是盗版

**Comment by poly-1** [comment]
行吧，看了半天源码，发现最新版已经减少了reload()的调用，并且`protected void Reload()`里面没有`_ReTcpingLatencyAll()`了

你直接说新版不会自动延迟测试不就行了。。。旧版确实动不动就触发 reload 然后`_ReTcpingLatencyAll()`。。。。

**Comment by TheCGDF** [comment]
那我只能说你这人挺奇怪的。
自动tcping是在0.1.7中移除的，而0.1.7已经发布了一年有余，在2020.1发布之前，0.1.7一直就是最新版。
如果你在2020.1发布前下载并使用了0.1.5，那SSD应该提示你更新到0.1.7。
而你似乎完全不知道0.1.7的存在（否则也不会有这个issue），所以我推测你是在用某个[fork/机场私编译]版本，比如有人喜欢去掉全家桶检查机制或者其他什么癖好，我个人就已经见过n个这种版本了，所以他们发布的ssd可能还在使用比较旧的代码。
这样大体就可以解释为何你没有更新到0.1.7了。因此我在不排除以上可能性的情况下，提示你去看一下本仓库的release（```请确保自己下载的不是其他仓库的SSD```），也因此我没有把这个issue标记为stupid。
然后我觉得你这人挺奇怪的，正常人按照提示去release[看一眼更新日志/重新下载一下]就能解决问题，你却反向一头扎进源码和git history。。。
避开了我所有的预测和猜想。。。
高手，深不可测。。。我败了。。。

**Comment by poly-1** [comment]
好吧，非常感谢你的耐心答复。事情是这样的，我一直用的的确是0.1.7版，因为我一般下载东西都会下最新版，并且会对比校验值，电脑上的版本一直是0.1.7，校验值如下，
```
    File: ShadowsocksD.exe
     MD5: 92d5f51be8eefe01e3237ffc86e397c5
   SHA-1: 14fb62015c1ec93afc15fb069cf5122c88a719f4
 SHA-256: aecaaa1978150fc5df0ce50de7486bc65d7125f11cf4183ae4394cfa840cdc9a
```
刚对比了一下，跟github版本0.1.7的**exe**是吻合的。

可能是我没事总是点开订阅设置和服务器设置来看看，于是就会经常性的触发reload，于是看到列表里面就会经常pending了。我的第一条回复也说了

> 至少每次重启软件之后过段时间都会自动重测，从pending变成有具体数值的状态。能否把这个自动测试改为手动？

不过最新版测速按源码看，tcping应该全部改为手动了，也就没这个问题了。

另外歪个楼提个建议，建议release的时候附上 sha256 :)

另外，最新版2020.1似乎双击图标无法打开编辑服务器的窗口了（右键图标点编辑服务器也无法打开），其他功能正常，似乎也是个玄学问题，之前用着还没问题。错误如下，

![image](https://user-images.githubusercontent.com/57432575/72454569-1281bc80-37fc-11ea-8836-432e8ffb47c8.png)

**Comment by TheCGDF** [comment]
关于sha256，我的看法是：只要你不用360浏览器这种“隐藏ssl证书还强行加入自己颁发给自己的证书”的屑浏览器，通过正规点的浏览器和HTTPS，下载下来的文件也一定是完整可靠的。所以我不认为提供sha256（或者其他什么）再验证一次有什么太大作用。
至于屑浏览器的用户，完全就已经不关心安全问题了，给了sha256也不会用。
关于那个Error稍后发布2020.3修复
