### ISSUE TITLE
win10的chrome 提示不让下载 检测到病毒

### ISSUE THREAD

**Issue by jinwyp** [TheCGDF/SSD-Windows#35]
win10的chrome 下载就失败， 提示  “失败-检测到病毒”

**Comment by TheCGDF** [comment]
@jinwyp 那建议放弃哦

**Comment by TheCGDF** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/2754#issuecomment-572138418

```
4.1.9释放PAC文件的行为发生了改变，被杀毒软件误判
```

上游的锅
