### ISSUE TITLE
无法打开bug

### ISSUE THREAD

**Issue by personatopone** [TheCGDF/SSD-Windows#37]
[2020-02-14 15:49:15] Current language is: ja-JP
[2020-02-14 15:49:15] Using ja translation for ja-JP
[2020-02-14 15:49:15] [E] System.TypeInitializationException: “Shadowsocks.Controller.I18N”的类型初始值设定项引发异常。 ---> System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Shadowsocks.Controller.I18N.Init(String res, String locale)
   在 Shadowsocks.Controller.I18N..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Controller.I18N.GetString(String key, Object[] args)
   在 Shadowsocks.View.MenuViewController.CreateMenuItem(String text, EventHandler click)
   在 Shadowsocks.View.MenuViewController.LoadMenu()
   在 Shadowsocks.View.MenuViewController..ctor(ShadowsocksController controller)
   在 Shadowsocks.Program.Main(String[] args)

 环境：windows1909

**Comment by TheCGDF** [comment]
fixed:https://github.com/TheCGDF/SSD-Windows/commit/e4bb1c05a992ff8a38b0144e65f2b65d1db85c6f


[SSD-2020.4-x86.zip](https://github.com/TheCGDF/SSD-Windows/files/4203634/SSD-2020.4-x86.zip)

**Comment by EdCeran** [comment]
最新是否有订阅链接失败的问题，我下载后无法订阅链接，提示订阅失败，经过测试订阅链接并没有问题
