### ISSUE TITLE
system.componentModel.win32Exception

### ISSUE THREAD

**Issue by whelamc** [TheCGDF/SSD-Windows#38]
环境
win32
NET Framework 4.7.2
VC2015

版本 2020.4-x86

具体
[2020-02-29 09:17:08] [E] Failed to start SIP003 plugin: 插件程序
[2020-02-29 09:17:08] System.ApplicationException: 插件程序 ---> System.ComponentModel.Win32Exception: 指定的可执行文件不是此操作系统平台的有效应用程序。
   在 System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start()
   在 Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Shadowsocks.Controller.Service.Sip003Plugin.StartIfNeeded()
   在 Shadowsocks.Controller.ShadowsocksController.GetPluginLocalEndPointIfConfigured(Server server)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()

**Comment by TheCGDF** [comment]
@whelamc 使用的插件是？

**Comment by whelamc** [comment]
> @whelamc 使用的插件是？

没有使用 运行SSD就报这个错

**Comment by whelamc** [comment]
@TheCGDF 
没有使用 运行SSD就报这个错

**Comment by TheCGDF** [comment]
@whelamc 是否可以提供一下gui-config.json的内容（请隐藏ip信息和订阅信息）？

**Comment by whelamc** [comment]
{
  "version": "2020.4",
  "configs": [
    {
      "server": "www.baidu.com",
      "server_port": -1,
      "password": "",
      "method": "",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "",
      "timeout": 5,
      "id": -1,
      "ratio": 0.0,
      "Latency": -1,
      "subscription_url": ""
    },
  ],
  "strategy": null,
  "index": 8,
  "global": false,
  "enabled": true,
  "shareOverLan": false,
  "isDefault": false,
  "isIPv6Enabled": false,
  "localPort": 7891,
  "portableMode": true,
  "showPluginOutput": true,
  "pacUrl": null,
  "gfwListUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": true,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Consolas, 8pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  },
  "subscriptions": [

  ]
}

**Comment by whelamc** [comment]
simple-obfs

**Comment by TheCGDF** [comment]
我觉得你提供的gui-config.json是不是有点问题。。。那个simple-obfs也没体现在里面啊？

**Comment by whelamc** [comment]
{
      "server": "xxxx",
      "server_port": xxxx,
      "password": "xxxx",
      "method": "chacha20-ietf-poly1305",
      "plugin": "simple-obfs",
      "plugin_opts": "obfs=tls;obfs-host=4743d6265.microsoft.com",
      "plugin_args": "",
      "remarks": "俄罗斯",
      "timeout": 5,
      "id": 1,
      "ratio": 0.1,
      "Latency": -1,
      "subscription_url": "xxx"
    }

我找出问题了
simple-obfs官方没有提供32位的插件

找了个非官方的32就解决了
https://github.com/imgk/simple-obfs-Cygwin/releases/tag/v0.0.5

**Comment by TheCGDF** [comment]
已修复:https://github.com/TheCGDF/SSD-Windows/commit/46a4f0c34b7422ff230565a8dde61bb58dfdd6f5

[SSD-2020.4-x86.zip](https://github.com/TheCGDF/SSD-Windows/files/4270059/SSD-2020.4-x86.zip)
