### ISSUE TITLE
在服务器列表中选择的服务器与实际使用的服务器不一致

### ISSUE THREAD

**Issue by mxyd233** [TheCGDF/SSD-Windows#41]
比如在服务器列表中选择第三个 实际使用的服务器是服务器列表中的第二个，选择第一个实际使用的是用于显示剩余流量(服务器为www-baidu.com:-1)的服务器。从鼠标指向TrayIcon显示的NotifyText也可以看出不一致。

**Comment by TheCGDF** [comment]
退出ssd，删除gui-config.json然后重新打开ssd重新订阅试一下

**Comment by mxyd233** [comment]
试了一下 还是不行

**Comment by TheCGDF** [comment]
是否可以截图看下服务器列表，机场名可以打码

**Comment by mxyd233** [comment]
![image](https://user-images.githubusercontent.com/21058757/77132297-df78d500-6a99-11ea-9c6c-5e4d777055e3.png)

**Comment by TheCGDF** [comment]
so。。。你说的用于显示剩余流量的www.baidu.com:-1节点在哪里？

**Comment by mxyd233** [comment]
刚才删除了gui-config.json后发现www.baidu.com:-1是ssd的默认生成的配置，当我选中上图"Lv1 台湾Hinet 01"服务器时，指向指向TrayIcon显示正在使用的服务器就是www.baidu.com:-1
![image](https://user-images.githubusercontent.com/21058757/77132830-ca04aa80-6a9b-11ea-91fc-9eee79e06fbf.png)
![image](https://user-images.githubusercontent.com/21058757/77132888-0d5f1900-6a9c-11ea-9277-c1bc27d9134c.png)
删除默认生成的www.baidu.com:-1配置后就没问题了

**Comment by TheCGDF** [comment]
今天才想起来这茬，确实是个BUG。。。
Fixed: https://github.com/TheCGDF/SSD-Windows/commit/5a3e274710e8da81588c8a37cdcfc8f204c8cade

[SSD-2020.4.zip](https://github.com/TheCGDF/SSD-Windows/files/4555657/SSD-2020.4.zip)
